Traceback (most recent call last):
  File "/home/dgjengen/.pling/dg-prosjekt/pling-project/main.py", line 3, in <module>
    from mbed import mbed
  File "/home/dgjengen/.pling/dg-prosjekt/pling-project/mbed.py", line 3, in <module>
    import serial
ImportError: No module named serial
Traceback (most recent call last):
  File "/home/dgjengen/.pling/dg-prosjekt/plingOmeter-project/plingOmeter.py", line 4, in <module>
    import Tkinter
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
Traceback (most recent call last):
  File "/home/dgjengen/.pling/dg-prosjekt/pling-project/main.py", line 3, in <module>
    from mbed import mbed
  File "/home/dgjengen/.pling/dg-prosjekt/pling-project/mbed.py", line 3, in <module>
    import serial
ImportError: No module named serial
Traceback (most recent call last):
  File "/home/dj/.pling/dg-prosjekt/pling-project/main.py", line 3, in <module>
    from mbed import mbed
  File "/home/dj/.pling/dg-prosjekt/pling-project/mbed.py", line 3, in <module>
    import serial
ImportError: No module named serial
Traceback (most recent call last):
  File "/home/dj/.pling/dg-prosjekt/plingOmeter-project/plingOmeter.py", line 4, in <module>
    import Tkinter
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
Traceback (most recent call last):
  File "/home/dj/.pling/dg-prosjekt/pling-project/main.py", line 3, in <module>
    from mbed import mbed
  File "/home/dj/.pling/dg-prosjekt/pling-project/mbed.py", line 3, in <module>
    import serial
ImportError: No module named serial
Traceback (most recent call last):
  File "/home/dj/.pling/dg-prosjekt/plingOmeter-project/plingOmeter.py", line 4, in <module>
    import Tkinter
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
Traceback (most recent call last):
  File "/home/dj/.pling/dg-prosjekt/pling-project/main.py", line 3, in <module>
    from mbed import mbed
  File "/home/dj/.pling/dg-prosjekt/pling-project/mbed.py", line 3, in <module>
    import serial
ImportError: No module named serial
Traceback (most recent call last):
  File "/home/dj/.pling/dg-prosjekt/plingOmeter-project/plingOmeter.py", line 4, in <module>
    import Tkinter
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
Traceback (most recent call last):
  File "/home/dj/pling/dg-prosjekt/pling-project/main.py", line 3, in <module>
    from mbed import mbed
  File "/home/dj/pling/dg-prosjekt/pling-project/mbed.py", line 3, in <module>
    import serial
ImportError: No module named serial
Traceback (most recent call last):
  File "/home/dj/pling/dg-prosjekt/pling-project/main.py", line 3, in <module>
    from mbed import mbed
  File "/home/dj/pling/dg-prosjekt/pling-project/mbed.py", line 3, in <module>
    import serial
ImportError: No module named serial
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e g happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
[00005602befafbc0] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e g happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
[00005602befcb420] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
